### ISSUE TITLE
[Suggestion] Yo-Kai by Number

### ISSUE THREAD

**Issue by rpalmon** [togenyan/Yo-kai_Editor_2#2]
Can you do what you did with the latest update of the Yo-Kai 3 editor with having the Yo-Kai in order by number? It would be very useful since I don't know Japanese.

**Comment by rpalmon** [comment]
Can you update it with the yokai in order by number or a search function for items?

**Comment by togenyan** [comment]
19ccde1
ca7fcdc
and v0.2.1
