### ISSUE TITLE
[Suggestions] add Moximous N Moximous K, Illuminoct, Darkyubi and ability to change a yokai's personality

### ISSUE THREAD

**Issue by KingEnma** [togenyan/Yo-kai_Editor_2#4]
can you add moximous N and K (spector guts F an K), illuminoct(hikari orochi) Dark Kyubi(Yami Kyuubi) and a button/ option that can allow is to change a yokai's personality

**Comment by togenyan** [comment]
Currently 妖怪ガッツF, 妖怪ガッツK, ヒカリオロチ, and ヤミキュウビ are available only in Japanese version of YW2. So they will be displayed in the combobox only when your OS language is set to Japanese.

> a button/ option that can allow is to change a yokai's personality
added in version 0.4.
