### ISSUE TITLE
Save edit is not showing on my game 

### ISSUE THREAD

**Issue by Orionsilver** [togenyan/Yo-kai_Editor_2#6]
try so hard to edit my save and watch a video and i did the same thing over and over and still is not showing on my game 
i use JKSM and still import back in my game and still is not show the edit i made
help me PLZ 
Save Zip File is Below
[Yo-kai watch bony spirits.zip](https://github.com/togenyan/Yo-kai_Editor_2/files/1253428/Yo-kai.watch.bony.spirits.zip)

**Comment by Orionsilver** [comment]
i'm using a USA Version

**Comment by togenyan** [comment]
Make sure you clicked the "Apply" button before saving. If the issue persists, please let me know what you tried in detail.

**Comment by Orionsilver** [comment]
I did the apply and still the same result

**Comment by togenyan** [comment]
* Komasan S (コマさんS) is only available in Psychic Specters, the third version of YW2.
* You have to edit the save data, not the extdata.

**Comment by Orionsilver** [comment]
i see 
i will check it now 
and reply u back as soon i see on the menu of the game

**Comment by Orionsilver** [comment]
it work thx

**Comment by Orionsilver** [comment]
i was doing extdata 
my bad 
and when u said save file 
and export and edit holy exporb 
and i test if it work and it work as a charm 👍 🥇
